"""
Project API routes.

Generated by: npm run new-module project
"""

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.auth import AuthPrincipal, get_current_user
from api.db.engine import get_db
from api.db.models import Project
from api.tenant import get_company_id


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------
class ProjectCreate(BaseModel):
    name: str = Field(min_length=1, max_length=255)


class ProjectResponse(BaseModel):
    id: int
    name: str
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
router = APIRouter(prefix="/project", tags=["project"])


@router.get("", response_model=list[ProjectResponse])
async def list_project(
    db: AsyncSession = Depends(get_db),
    company_id: int = Depends(get_company_id),
):
    result = await db.execute(
        select(Project)
        .where(Project.company_id == company_id)
        .order_by(Project.created_at.desc(), Project.id.desc())
    )
    return result.scalars().all()


@router.post("", response_model=ProjectResponse, status_code=status.HTTP_201_CREATED)
async def create_project(
    payload: ProjectCreate,
    db: AsyncSession = Depends(get_db),
    principal: AuthPrincipal = Depends(get_current_user),
):
    row = Project(name=payload.name.strip(), company_id=principal.company_id)
    db.add(row)
    await db.commit()
    await db.refresh(row)
    return row


@router.delete("/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_project(
    item_id: int,
    db: AsyncSession = Depends(get_db),
    company_id: int = Depends(get_company_id),
):
    result = await db.execute(
        select(Project).where(Project.id == item_id, Project.company_id == company_id)
    )
    row = result.scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found")
    await db.delete(row)
    await db.commit()
